### ISSUE TITLE
Not able to get Final Grade for an Assigment

### ISSUE THREAD

**Issue by nsheehan** [newroco/moodle-multigraders#1]
Thank you for your work on this plugin. I have started testing this morning to see if it will allow us to have two teachers grade a submission and so far I have not been able to get a final grade with the following config:
Assignment 2 - Grading Method Ready for use
Multiple Markers for Assignment 2
Secondary graders defined: Teachy McTeacher, Niall Sheehan.
The student can also see all secondary feedback when the grade is final.
Method of auto calculating the next grade and outcomes: average over previous grades

Two teachers have submitted grades and comments however the assignment is still showing Not Graded. See [link for screenshot](https://dev.myobh.ca/images/notgraded.jpg).

Based on the instructions "When the defined number of graders is met, another grader may award the final one by looking at the grades and feedback from the previous graders."

I have had two graders grade the assignment and the 3rd looked at the results (screenshot is the 3rd viewer), yet the grade is still not final.

Please advise.

**Comment by lucianpricop** [comment]
Hi. Thanks for taking the time to report this, unfortunately we were still working and we have a stable version now. 
You can test it here https://testmoodle.newro.co
Users:
teacher_01
teacher_02
student_01
student_02

Password ( all of them have the same password ):
redM!ce57
